// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADIPgby-l7uAz23jIrBSED0xuJATIcryc',
    appId: '1:732161898983:web:ed5c6f82ad32706d6c6542',
    messagingSenderId: '732161898983',
    projectId: 'fitquest-e4d3c',
    authDomain: 'fitquest-e4d3c.firebaseapp.com',
    storageBucket: 'fitquest-e4d3c.firebasestorage.app',
    measurementId: 'G-8G4YC5WBGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ45g4tlm12jF6yN2Ua9rK3m07-lVXJKI',
    appId: '1:732161898983:android:06e5f78eb3fa3a966c6542',
    messagingSenderId: '732161898983',
    projectId: 'fitquest-e4d3c',
    storageBucket: 'fitquest-e4d3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoj9ctwmobQKSO3hYk0roDRHShMa2y2UE',
    appId: '1:732161898983:ios:4abfa9a8426f9ef06c6542',
    messagingSenderId: '732161898983',
    projectId: 'fitquest-e4d3c',
    storageBucket: 'fitquest-e4d3c.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoj9ctwmobQKSO3hYk0roDRHShMa2y2UE',
    appId: '1:732161898983:ios:4abfa9a8426f9ef06c6542',
    messagingSenderId: '732161898983',
    projectId: 'fitquest-e4d3c',
    storageBucket: 'fitquest-e4d3c.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADIPgby-l7uAz23jIrBSED0xuJATIcryc',
    appId: '1:732161898983:web:07c354db060c03056c6542',
    messagingSenderId: '732161898983',
    projectId: 'fitquest-e4d3c',
    authDomain: 'fitquest-e4d3c.firebaseapp.com',
    storageBucket: 'fitquest-e4d3c.firebasestorage.app',
    measurementId: 'G-4R1RB7LDWM',
  );
}
